### ISSUE TITLE
sudoers.j2: Ansible commands with PATH

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/harden.sh#87]
If Ansible has `PATH` configured e.g. as follows:

```
---
- name: Harden
  hosts: localhost
  vars_files:
    - vars.yml
  environment:
    PATH: /usr/sbin:/usr/bin:/sbin:/bin
```

It affects the command sent to `sudo`:

```
Feb 20 18:55:52 darkstar sudo[9194]: pyllyukko : command not allowed ; TTY=pts/1 ; PWD=/home/pyllyukko ; USER=root ; COMMAND=/bin/sh -c 'echo BECOME-SUCCESS-zabzlirtolwgxfyuezgqvxwkxsfzlzzh ; PATH=/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/python3 /home/pyllyukko/.ansible/tmp/ansible-tmp-1740077754.0195405-30102-246572524616157/AnsiballZ_slackpkg.py'
```

Somewhat related to #31, as we started messing with the `PATH` :P
